#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=10
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --constraint=knl



module load hpctoolkit/2021.03.01

hpcstruct -j 8 build/bin/xhpcg

ranks=8

srun -n $ranks  --cpu-bind=cores \
    hpcprof-mpi -S xhpcg.hpcstruct \
		--metric-db yes \
		-o hpctoolkit-xhpcg.d \
		hpctoolkit-xhpcg.m
