#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=10
#SBATCH --nodes=2
#SBATCH --tasks-per-node=8
#SBATCH --cpus-per-task=8
#SBATCH --constraint=knl

# use LLVM OpenMP Tools support
module use /global/common/software/m1759/hpctoolkit-install/2021.03/modules
module load openmp/ompt

module load hpctoolkit/2021.03.01

# export OMP_PROC_BIND=true
# export OMP_PLACES=threads
export OMP_NUM_THREADS=8

export OMP_WAIT_POLICY=active

module load hpctoolkit/2021.03.01

export HPCRUN_ARGS="-o hpctoolkit-xhpcg.m -e CPUTIME -t"
export ranks=16

bind=--cpu-bind=cores 
size=32

srun -n $ranks $bind  \
    hpcrun ${HPCRUN_ARGS} build/bin/xhpcg  --nx=$size --rt=30

