#!/bin/sh

# Sample launch script for hpcprof-mpi.  Use hpcprof-mpi (on compute
# nodes) instead of hpcprof (front-end) for (1) large runs with many
# procs/threads, or (2) computing rank/thread level metrics for 
# graphing and inspection.

ranks=8
ranks_per_node=2

export HPCTOOLKIT_PATH=/soft/perftools/hpctoolkit/spack-2020-08/packages/linux-rhel7-x86_64/gcc-8.2.0/hpctoolkit-2020.08.03-v5hh7hlsrvsqzqtalwk27freiuut2a55/bin

export PATH=${HPCTOOLKIT_PATH}:${PATH}

mpirun -f ${COBALT_NODEFILE} -n $ranks  -ppn $ranks_per_node  \
    hpcprof-mpi  \
    	-S amg2006.hpcstruct  \
    	-o hpctoolkit-amg2006.d \
    	--metric-db  yes  \
    	hpctoolkit-amg2006.m
