#!/bin/bash
#SBATCH --qos=regular
#SBATCH --time=5
#SBATCH --nodes=2
#SBATCH --tasks-per-node=8
#SBATCH --cpus-per-task=8
#SBATCH --constraint=knl

# use LLVM OpenMP Tools support
module use /global/common/software/m1759/hpctoolkit-install/2021.03/modules
module load openmp/ompt

module load hpctoolkit/2021.03.01

export OMP_PROC_BIND=true
export OMP_PLACES=threads
export OMP_NUM_THREADS=8

export OMP_WAIT_POLICY=active

module load hpctoolkit/2021.03.01

export HPCRUN_ARGS="-o hpctoolkit-amg2013.m -e REALTIME -t"
export ranks=16
# export OMP_TOOL=disabled

bind=--cpu-bind=cores 

refine=20

srun -n $ranks $bind  \
    hpcrun ${HPCRUN_ARGS} AMG2013/test/amg2013  -P 2 4 2  -r  $refine $refine $refine
