#!/bin/sh

# Sample launch script for amg2013 + hpctoolkit on cray

# Submit this with your job manager with arguments that specify
#   time = 12 minutes
#   nodes = 4

ranks=8
ranks_per_node=2
threads=5

# Hpcrun events to profile, separated by space.
# See 'hpcrun -L' for a list of possible events.
#export HPCRUN_EVENT_LIST='REALTIME@8000'

# Turn tracing on.
#export HPCRUN_TRACE=1

export HPCRUN_ARGS="-o hpctoolkit-amg2013.m -e REALTIME@8000 -t"

# Turn sampling off until started in the program.
# Don't use this without hpctoolkit_sampling_start().
# export HPCRUN_DELAY_SAMPLING=1

# For large runs, use this to limit the total number of threads to at
# most a few thousand (in this case, 10%).
# export HPCRUN_PROCESS_FRACTION=0.10

export OMP_NUM_THREADS="$threads"

export OMP_WAIT_POLICY=active
export KMP_AFFINITY=none

# module load hpctoolkit
# export HPCTOOLKIT_PATH=/gpfs/mira-home/johnmc/atpesc2020-cooley/spack-cooley-2020-08/opt/spack/linux-rhel7-x86_64/gcc-8.2.0/hpctoolkit-2020.08.03-v5hh7hlsrvsqzqtalwk27freiuut2a55/bin

export HPCTOOLKIT_PATH=/soft/perftools/hpctoolkit/spack-2020-08/packages/linux-rhel7-x86_64/gcc-8.2.0/hpctoolkit-2020.08.03-v5hh7hlsrvsqzqtalwk27freiuut2a55/bin

export PATH=${HPCTOOLKIT_PATH}:${PATH}
# export LD_LIBRARY_PATH=/soft/perftools/hpctoolkit/openmp-ompt/lib:$LD_LIBRARY_PATH

mpirun -f ${COBALT_NODEFILE} -n $ranks  -ppn $ranks_per_node  \
    hpcrun ${HPCRUN_ARGS} AMG2013/test/amg2013  -P 2 2 2  -r  20 20 20
