#!/bin/sh

#------------------------------------------------------------------------------------
# a shell script to submit an hpcprof-mpi job to analyze a medium-sized performance 
# database on BG/Q
#------------------------------------------------------------------------------------
usage()
{
echo "usage: bgq-analyze <project> <executable-name> <measurements-jobid> <machine>" 
exit -1
}
if test -z "$1"; then
usage
fi

PROJECT=$1

if test -z "$2"; then
usage
fi

APPL=$2

if test -z "$3"; then
usage
fi

JID=$3

if test -z "$4"; then
usage
fi

if test "$4" = "vesta"; then
machine=vesta
fi

if test "$4" = "cetus"; then
machine=mira
fi

if test -z "$machine"; then
echo unknown machine: $4
exit -1
fi


S=${APPL}.hpcstruct

if ! test -f ${S}; then
  echo no structure file for the application \'${APPL}\'. 
  echo please create one by running the command \'hpcstruct ${APPL}\'
  echo aborting analysis.
  exit -1
fi

M=hpctoolkit-${APPL}-measurements-${JID}

if ! test -d ${M}; then
  echo no measurements directory with the expected name \'${M}\'
  echo aborting analysis.
  exit -1
fi


TIME=00:15:00
PC=16
MODE=c1
NODES=16

EXEC=/projects/Tools/hpctoolkit/pkgs-${machine}/hpctoolkit/bin/hpcprof-mpi
ARGS="-S ${S} ${M}"

echo qsub -A ${PROJECT} -n ${NODES} --mode ${MODE} --proccount ${PC} --cwd `pwd` -t ${TIME} ${EXEC} ${ARGS}
qsub -A ${PROJECT} -n ${NODES} --mode ${MODE} --proccount ${PC} --cwd `pwd` -t ${TIME} ${EXEC} ${ARGS}
